Really rename oz-examples.1 to oz-examples.5
9832cd038efdd39fa58f0b156d53c57b71a929d0 did all the work around
this, but...didn't actually rename the source file, which causes
install to blow up because it looks for a non-existent file:

error: can't copy 'man/oz-examples.5': doesn't exist or not a regular file

Signed-off-by: Adam Williamson <awilliam@redhat.com>