Add video nome to the libvirt xml
Otherwise we can end up with some error like:
Traceback (most recent call last):
 File "/bin/oz-install", line 162, in <module>
     libvirt_xml = guest.install(timeout, force_download)
 File "/usr/lib/python2.7/site-packages/oz/Windows.py", line 232, in install
     return self._do_install(internal_timeout, force, 2)
 File "/usr/lib/python2.7/site-packages/oz/Guest.py", line1713, in _do_install
     dom = self.libvirt_conn.createXML(xml, 0)
 File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3727, in createXML
     if ret is None:raise libvirtError('virDomainCreateXML() failed', conn=self)
 libvirt.libvirtError: unsupported configuration: non-primary video device must be type of 'qxl'